[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "ldap"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = true
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = false
# set to the path to your root CA certificate or leave unset to use system defaults
root_ca_cert = "/opt/certs/ca.pem"
# Authentication against LDAP servers requiring client certificates
client_cert = "/opt/certs/ldap.crt"
client_key = "/opt/certs/ldap.key"

# Search user bind dn
bind_dn = "uid=read,ou=Users,dc=lihuaio,dc=com"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = '123'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
# Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
search_filter = "(uid=%s)"

# An array of base dns to search through
search_base_dns = ["ou=Users,dc=lihuaio,dc=com"]

# group_search_filter = "(&(objectClass=groupOfNames)(cn=%s))"
# group_search_filter_user_attribute = "distinguishedName"
group_search_base_dns = ["cn=grafana,ou=Groups,dc=lihuaio,dc=com"]

# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
member_of = "memberOf"
email =  "mail"
name = "displayName"
surname = "sn"
username = "cn"
[[servers.group_mappings]]
group_dn = "cn=super,cn=grafana,ou=Groups,dc=lihuaio,dc=com"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=editor,cn=grafana,ou=Groups,dc=lihuaio,dc=com"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "cn=viewer,cn=grafana,ou=Groups,dc=lihuaio,dc=com"
org_role = "Viewer"